name: workproject
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.2.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=16.1.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bson=0.5.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cachelib=0.9.0
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.19.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.2.0
  - cryptography=43.0.0
  - cycler=0.11.0
  - cymem=2.0.8
  - cyrus-sasl=2.1.28
  - cython-blis=0.7.10
  - dataclasses=0.8
  - datasets=2.19.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - dnspython=2.4.2
  - email-validator=2.2.0
  - email_validator=2.2.0
  - executing=0.8.3
  - fastapi=0.115.2
  - fastapi-cli=0.0.5
  - filelock=3.13.1
  - flake8=7.1.1
  - flask=3.0.3
  - flask-session=0.8.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gensim=4.3.3
  - gettext=0.21.0
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - iniconfig=1.1.1
  - ipykernel=6.28.0
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jiter=0.6.1
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langcodes=3.3.0
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.9.1
  - libcxx=19.1.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.27
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsentencepiece=0.2.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=19.1.2
  - lz4-c=1.9.4
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=2.0.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgspec=0.18.6
  - multidict=6.0.4
  - multiprocess=0.70.15
  - murmurhash=1.0.10
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.9.1
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.51.2
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pep8=1.7.1
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - preshed=3.0.9
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pybind11-abi=5
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyparsing=3.1.2
  - pypdf=4.2.0
  - pypdf2=3.0.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-multipart=0.0.9
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=2.3.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.8.1
  - rpds-py=0.10.6
  - safetensors=0.4.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - sentence-transformers=3.2.0
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=75.1.0
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.5.1
  - smart-open=7.0.4
  - smart_open=7.0.4
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.5
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.2.0
  - starlette=0.38.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - terminado=0.17.1
  - thinc=8.2.5
  - threadpoolctl=3.5.0
  - tiktoken=0.8.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tokenizers=0.19.1
  - torchvision=0.18.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.44.1
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - uvicorn=0.20.0
  - wasabi=1.1.2
  - wcwidth=0.2.5
  - weasel=0.4.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - wrapt=1.16.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5